### ISSUE TITLE
accordproject-studio.md: Broken image

### ISSUE THREAD

**Issue by fr1sk** [accordproject/techdocs#178] opened 2019-10-16 13:30 UTC
Image `studio.png` is broken inside `accordproject-studio.md` doc file

**Comment by fr1sk** [comment] 2019-10-16 13:30
I will be on it

**Comment by fr1sk** [comment] 2019-10-16 13:45
fixed

**Comment by jeromesimeon** [comment] 2019-10-16 16:47
@fr1sk I am a bit confused by this issue. I _think_ that page is obsolete and not actually built as part of the Web site. Could you provide a snapshot of the issue from the documentation site itself?

**Comment by fr1sk** [comment] 2019-10-16 17:17
![image](https://user-images.githubusercontent.com/15851195/66942547-9f747880-f049-11e9-9b07-ee2f495d7e7c.png)
@jeromesimeon

**Comment by jeromesimeon** [comment] 2019-10-16 17:20
@fr1sk I meant in the Web site: https://docs.accordproject.org

**Comment by irmerk** [comment] 2019-10-16 17:27
Same as @jeromesimeon, I'm not sure where the issue is or how #179 is fixing it.

**Comment by jeromesimeon** [comment] 2019-10-19 20:36
I still don't think this is an issue. I'm closing this.

**Closed by jeromesimeon** 2019-10-19 20:36 UTC
Labels: Resolution: Unsolved 🔮, Type: Question ❓
