### ISSUE TITLE
Documentation broken link, page not found error

### ISSUE THREAD

**Issue by sofiter** [accordproject/techdocs#329] opened 2020-11-26 19:09 UTC
**Describe the bug**
Some links are broken

**To Reproduce**
1. Go to https://docs.accordproject.org/docs/logic-ergo.html
2. Click on the Accord Project Template Specification hyperlink
3. A page not found is returned

**Expected behavior**
The link should redrect to the according page

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome
 - Version 87.0.4280.66

**Comment by Aniruddha-Shriwant** [comment] 2021-02-20 05:32
@irmerk , I think the issue is not resolved because I also tried the steps to reproduce this behavior and got the following :

![image](https://user-images.githubusercontent.com/58624108/108584910-fdfee480-736a-11eb-8002-6721252d4562.png)

**Comment by Aniruddha-Shriwant** [comment] 2021-02-20 05:41
Should "Accord Project Template Specification hyperlink" point to [this](https://docs.accordproject.org/docs/ref-ergo-spec.html)

**Comment by dselman** [comment] 2021-02-20 06:21
Yes, please submit PRs to fix the links and I will approve. No need to fix old versions of the site - just fix the md files under `/docs` (switch to `next` version to view your changes).

**Comment by Aniruddha-Shriwant** [comment] 2021-02-20 07:21
Hello, I apologize for this naive doubt
I had updated `techdocs/docs/logic-ergo.md` and after that had run this commands : 

```
PS D:\Github\techdocs\website> npm run version next

> @ version D:\Github\techdocs\website
> docusaurus-version "next"

Version next created!

PS D:\Github\techdocs\website> npm run start

> @ start D:\Github\techdocs\website
> docusaurus-start

LiveReload server started on port 35729
Docusaurus server started on port 3000
```

After running this the broken link was fixed but when I run `git status` I got following : 
```
PS D:\Github\techdocs\website> git status
On branch aniruddha/i329/broken-link
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   ../docs/logic-ergo.md
        modified:   i18n/en.json
        modified:   versions.json

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        versioned_docs/version-next/
        versioned_sidebars/version-next-sidebars.json

no changes added to commit (use "git add" and/or "git commit -a")
PS D:\Github\techdocs\website>
```

So all these files that are modified/created are they normal when we change/edit md files or I had done something wrong?

**Comment by dselman** [comment] 2021-02-20 07:28
You should just update the .md files. We will release the next version of the documentation when a useful batch of changes have been committed.

You can *view* the `next` version with your changes by opening the local site in your browser (`npm run start` within the `website` folder) and then clicking on the 0.21 version link in the header, and then selecting "unstable > Documentation"

**Comment by Aniruddha-Shriwant** [comment] 2021-02-20 07:32
Okay, thanks!

**Comment by Aniruddha-Shriwant** [comment] 2021-02-21 04:35
@dselman should I work on #328 ?

**Comment by irmerk** [comment] 2021-02-22 19:22
@Aniruddha-Shriwant sure just add them both to the same PR that's open.

**Comment by Aniruddha-Shriwant** [comment] 2021-02-22 19:34
Okay! @irmerk :)

**Closed** 2021-03-04 22:06 UTC
Labels: Type: Bug 🐛
